### ISSUE TITLE
Install instructions incorrect

### ISSUE THREAD

**Issue by mgmhunt** [cathei/BakingSheet#29]
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/cathei/BakingSheet.git?path=UnityProject/Packages/com.cathei.bakingsheet#v4.1.1 ]:
  Error when executing git command. fatal: Invalid refspec 'v4.1.1 '
 [UpmError_NotFound].

Removing #v4.1.1 from package GIT install works. ie 

https://github.com/cathei/BakingSheet.git?path=UnityProject/Packages/com.cathei.bakingsheet

**Comment by cathei** [comment]
Thank you for putting your time into making issue. The path below works.
```
https://github.com/cathei/BakingSheet.git?path=UnityProject/Packages/com.cathei.bakingsheet#v4.1.1
```
Seems like you have accidentally put additional whitespace at the end of the path which makes Unity confused.
I'll close this issue. Let me know if you encounter different issue!
