### ISSUE TITLE
Error importing if Microsoft.Extensions.Logging.Abstractions.dll already exists in project

### ISSUE THREAD

**Issue by mgmhunt** [cathei/BakingSheet#30]
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name Microsoft.Extensions.Logging.Abstractions.dll included on the current platform. Only one assembly with the same name is allowed per platform.

Moving package to root Packages folder and removing Microsoft.Extensions.Logging.Abstractions.dll from the package allows compile.

**Comment by cathei** [comment]
Thank you for reporting.

I've added `BAKINGSHEET_EXTERNAL_LOGGING_DLL` define constraint you can add in Project Settings. Defining it will disable BakingSheet's embedded `Microsoft.Extensions.Logging.Abstractions.dll`.
