### ISSUE TITLE
Issue with a complex data structure

### ISSUE THREAD

**Issue by laicasaane** [cathei/BakingSheet#34]
Hi, could you tell any problem with this data? It doesn't work however I try. The exported file `Skills.json` is always empty.
https://github.com/laicasaane/BakingSheet/commit/330e426e01594451bb16818520faa779f57e03be

**Comment by cathei** [comment]
Seems like your `xlsx` contains empty row - which BakingSheet consider as end of the file. (I have not found a better way to detect yet.)

**Comment by laicasaane** [comment]
I've implemented something called `empty row streak threshold` to allow bypassing a number of empty rows before considering it's the end of file. Using this implementation for a while makes me forget that the original BakingSheet doesn't have that mechanism.

https://github.com/Zitga-Tech/ZBase.Foundation.Data/blob/e79ff18bad5e3892a38f2155acfdd9ce788b46a8/Packages/ZBase.Foundation.Data/Data.Authoring/Converters/DatabaseRawSheetImporter.cs#L27C42-L27C42

**Comment by cathei** [comment]
I might adopt something like that in future.
